/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.team7.server;

import edu.duke.ece651.team7.server.model.Server;

public class App {
  public static void main(String[] args) {
    if (args.length == 3) {
      try {
        Server server = new Server(System.out, Integer.parseInt(args[0]), Integer.parseInt(args[1]),
            Integer.parseInt(args[2]));
        server.start();
      } catch (Exception e) {
        System.err.println("Exception: " + e);
      }
    } else {
      System.err.println("Usage: server <port> <players number> <player's init units>");
    }
  }
}
