/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.team7.server;

public class App {
  public static void main(String[] args) {
    if (args.length == 2) {
      try {
        Server server = new Server(Integer.parseInt(args[0]), Integer.parseInt(args[1]), System.out);
      } catch (Exception e) {
        System.err.println("Exception: " + e);
      }
    } else {
      System.err.println("Usage: server <port> <MaxPlayerNumber>");
    }
  }
}
